services:
  jerrgen:
    build:
      context: ./generators/jerrgen
#    TODO: отключить в будущем, когда проверю, что фильтрация в векторе работает.
#    environment:
#      SPRING_MAIN_BANNER_MODE: "off"
    restart: unless-stopped # Перезапуск, если контейнер упал.
