services:
  kafka:
    image: apache/kafka:4.1.1
    environment:
      # Настройка KRaft (без ZooKeeper).
      KAFKA_NODE_ID: "1" # С одной нодой.
      KAFKA_PROCESS_ROLES: "broker,controller" # Нода и брокер, и контроллер.

      # Два слушателя.
      # INTERNAL - для контейнеров внутри errlog-core.
      # EXTERNAL - для внешних клиентов (например, реальных сервисов).
      KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093" # Слушатели.
      # Как нода будет объявлять себя клиентам (внутренним и внешним).
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://${ERRLOG_KAFKA_EXTERNAL_HOST:-localhost}:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL" # Имя слушателя для внутренней коммуникации между брокерами.
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" # Какой слушатель используется для роли controller.
      # Сопоставление имен слушателей с протоколами безопасности.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093" # Описание кворума контроллеров.

      # Настройки кластера, чтобы не было ошибок с репликацией в single-node.
      # Устанавливаем фактор репликации 1.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      # Для ускорения старта (убираем задержку перед ребалансом групп).
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

      # Отключаем автоматическое создание топика (будем создавать вручную).
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    ports:
      - "9094:9094" # Внешний слушатель для внешних клиентов.
    healthcheck: # Чтобы запускать vector и kafka-init только после успешного запуска kafka.
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: "unless-stopped"

  kafka-init:
    image: apache/kafka:4.1.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-lc" ]
    command: [ "sh /init/init.sh" ]
    volumes:
      - ./docker/kafka/init.sh:/init/init.sh:ro
    restart: "no"

  clickhouse:
    image: clickhouse/clickhouse-server:26.1
    environment:
      CLICKHOUSE_USER: "errlog_ch_user"
      CLICKHOUSE_PASSWORD: "errlog_ch_password"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1" # Для корректного создания пользователя.
    ports:
      - "8123:8123" # Порт для HTTP запросов.
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck: # Чтобы запускать ingestor и clickhouse-init только после успешного старта clickhouse.
      test: [ "CMD-SHELL", "clickhouse-client --host localhost --user errlog_ch_user --password errlog_ch_password --query 'SELECT 1' >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: "unless-stopped"

  clickhouse-init:
    image: clickhouse/clickhouse-server:26.1
    depends_on:
      clickhouse:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-lc" ]
    command: [ "clickhouse-client --host clickhouse --user errlog_ch_user --password errlog_ch_password --multiquery < /init/init.sql" ]
    volumes:
      - ./docker/clickhouse/init.sql:/init/init.sql:ro
    restart: "no"

  ingestor:
    build:
      context: ./ingestor
    depends_on: # Ждем, когда стартуют Kafka и ClickHouse.
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
      clickhouse-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC: "errors-raw"
      KAFKA_GROUP_ID: "errlog-ingestor"
      CLICKHOUSE_JDBC_URL: "jdbc:clickhouse://clickhouse:8123/errlog_ch"
      CLICKHOUSE_USER: "errlog_ch_user"
      CLICKHOUSE_PASSWORD: "errlog_ch_password"
    # Если нужно подключиться дебаггером.
    #      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    #    ports:
    #      - "5005:5005"
    restart: "unless-stopped"

  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_DB: "errlog_pg"
      POSTGRES_USER: "errlog_pg_user"
      POSTGRES_PASSWORD: "errlog_pg_password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck: # Чтобы запускать api только после успешного старта postgres.
      test: [ "CMD-SHELL", "pg_isready -U errlog_pg_user -d errlog_pg -h localhost >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: "unless-stopped"

  errapi:
    build:
      context: ./errapi
    depends_on: # Ждем, когда стартуют postgres и clickhouse.
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      clickhouse-init:
        condition: service_completed_successfully
    environment:
      POSTGRES_JDBC_URL: "jdbc:postgresql://postgres:5432/errlog_pg"
      POSTGRES_USER: "errlog_pg_user"
      POSTGRES_PASSWORD: "errlog_pg_password"

      CLICKHOUSE_JDBC_URL: "jdbc:clickhouse://clickhouse:8123/errlog_ch"
      CLICKHOUSE_USER: "errlog_ch_user"
      CLICKHOUSE_PASSWORD: "errlog_ch_password"

      ERRLOG_OWNER_LOGIN: "owner"
      ERRLOG_OWNER_EMAIL: "owner@example.com"
      ERRLOG_OWNER_PASSWORD: "owner_password"

      JWT_SECRET: "jwt-secret-that-should-be-more-than-32-symbols"
      JWT_EXPIRES_SECONDS: "315360000" # 10 лет.
    #      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" # Для подключения дебаггером.
    ports:
      - "8080:8080"
    #      - "5005:5005" # Для подключения дебаггером.
    restart: "unless-stopped"

volumes:
  postgres_data:
  clickhouse_data:
