# Определение источников.
sources:
  docker:
    type: docker_logs
    # Vector читает все контейнеры нашего стенда, но мы хотим читать только генераторы ошибок.
    # Поэтому фильтруем контейнеры на наличие специального лейбла.
    include_labels:
      - "errlog.collect=true"

# Определение трансформаций.
transforms:
  only_errlog_json_warn_error:
    type: remap
    inputs: [ "docker" ] # Связываем наш источник с нашей трансформацией.
    source: |
      # Получение названия сервиса из метаданных контейнера. В лейбл его помещает docker compose.
      service = .label."com.docker.compose.service"
      if is_null(service) { service = "unknown-service" }

      # Получение названия инстанса из метаданных контейнера.
      instance = .container_name
      if is_null(instance) { instance = "unknown-instance" }

      # Получение типа источников из метаданных контейнера.
      source_type = .label."errlog.source_type"
      if is_null(source_type) { source_type = "unknown" }

      # Получение версии сервиса из метаданных контейнера.
      service_version = .label."errlog.service_version"
      if is_null(service_version) { service_version = "unknown" }

      # Забираем исходное сообщение (далее где abort - пропуск лога).
      msg, err = to_string(.message)
      if err != null { abort }

      # Очищаем его от лишних пробелов.
      msg = strip_whitespace(msg)
      if msg == "" { abort }

      # Фильтруем НЕ JSON строки.
      if !starts_with(msg, "{") { abort }

      # Парсим JSON.
      parsed, err = parse_json(msg)
      if err != null { abort }

      # Далее работаем уже со спаршенным сообщением.
      . = parsed

      # Безопасно приводим уровень ошибки к строке (если что - пропустим).
      lvl, err = to_string(.level)
      if err != null { abort }

      # Оставляем только WARN и ERROR сообщения.
      lvl = upcase(lvl)
      if lvl != "WARN" && lvl != "ERROR" { abort }
      .level = lvl

      # Обогащаем событие метаданными контейнера.
      .service = service
      .instance = instance
      .sourceType = source_type
      .serviceVersion = service_version

# Определение потребителей.
sinks:
  kafka:
    type: kafka
    inputs: [ "only_errlog_json_warn_error" ] # Связываем нашу трансформацию с нашим кафка брокером.
    bootstrap_servers: "kafka:9092"
    topic: "errors-raw"
    encoding:
      codec: json # Записывать будем в виде JSON.
